# Setup Enviroment 

#docker pull mysql:latest
#docker pull wordpress:latest


version: '3.8'
services: 
  db: 
    image: mysql:latest
    container_name: mysql
    networks:
    - Monk_Net
    volumes: 
    - /data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=redhat
    - MYSQL_DATABASE=Monk_Blog
    - MYSQL_USER=SUSHIL
    - MYSQL_PASSWORD=redhat

  wordpress:
    depends_on: 
    - db
    image: wordpress:latest
    container_name: wordpress_container
    networks: 
    - Monk_Net
    ports: 
    - 8080:80
    environment:
    - MYSQL_ROOT_PASSWORD=redhat
    - MYSQL_DATABASE=Monk_Blog
    - MYSQL_USER=SUSHIL
    - MYSQL_PASSWORD=redhat



      
networks: 
  Monk_Net:
    driver: bridge 
